/*
 * PS2 Live Graph Studio - Embedded Asset Data (Generated)
 * DO NOT EDIT - Generated by generate_embedded_assets.sh
 */

#ifndef ASSETS_EMBEDDED_DATA_H
#define ASSETS_EMBEDDED_DATA_H

#include <stddef.h>

extern unsigned char asset_ui_cursor_png[];
extern unsigned int size_asset_ui_cursor_png;
extern unsigned char asset_ui_port_dot_png[];
extern unsigned int size_asset_ui_port_dot_png;
extern unsigned char asset_ui_port_in_png[];
extern unsigned int size_asset_ui_port_in_png;
extern unsigned char asset_ui_port_out_png[];
extern unsigned int size_asset_ui_port_out_png;
extern unsigned char asset_ui_node_bg_png[];
extern unsigned int size_asset_ui_node_bg_png;
extern unsigned char asset_icons_node_const_png[];
extern unsigned int size_asset_icons_node_const_png;
extern unsigned char asset_icons_node_time_png[];
extern unsigned int size_asset_icons_node_time_png;
extern unsigned char asset_icons_node_pad_png[];
extern unsigned int size_asset_icons_node_pad_png;
extern unsigned char asset_icons_node_noise_png[];
extern unsigned int size_asset_icons_node_noise_png;
extern unsigned char asset_icons_node_lfo_png[];
extern unsigned int size_asset_icons_node_lfo_png;
extern unsigned char asset_icons_node_add_png[];
extern unsigned int size_asset_icons_node_add_png;
extern unsigned char asset_icons_node_sub_png[];
extern unsigned int size_asset_icons_node_sub_png;
extern unsigned char asset_icons_node_mul_png[];
extern unsigned int size_asset_icons_node_mul_png;
extern unsigned char asset_icons_node_div_png[];
extern unsigned int size_asset_icons_node_div_png;
extern unsigned char asset_icons_node_mod_png[];
extern unsigned int size_asset_icons_node_mod_png;
extern unsigned char asset_icons_node_abs_png[];
extern unsigned int size_asset_icons_node_abs_png;
extern unsigned char asset_icons_node_neg_png[];
extern unsigned int size_asset_icons_node_neg_png;
extern unsigned char asset_icons_node_min_png[];
extern unsigned int size_asset_icons_node_min_png;
extern unsigned char asset_icons_node_max_png[];
extern unsigned int size_asset_icons_node_max_png;
extern unsigned char asset_icons_node_clamp_png[];
extern unsigned int size_asset_icons_node_clamp_png;
extern unsigned char asset_icons_node_map_png[];
extern unsigned int size_asset_icons_node_map_png;
extern unsigned char asset_icons_node_sin_png[];
extern unsigned int size_asset_icons_node_sin_png;
extern unsigned char asset_icons_node_cos_png[];
extern unsigned int size_asset_icons_node_cos_png;
extern unsigned char asset_icons_node_tan_png[];
extern unsigned int size_asset_icons_node_tan_png;
extern unsigned char asset_icons_node_atan2_png[];
extern unsigned int size_asset_icons_node_atan2_png;
extern unsigned char asset_icons_node_lerp_png[];
extern unsigned int size_asset_icons_node_lerp_png;
extern unsigned char asset_icons_node_smooth_png[];
extern unsigned int size_asset_icons_node_smooth_png;
extern unsigned char asset_icons_node_step_png[];
extern unsigned int size_asset_icons_node_step_png;
extern unsigned char asset_icons_node_pulse_png[];
extern unsigned int size_asset_icons_node_pulse_png;
extern unsigned char asset_icons_node_hold_png[];
extern unsigned int size_asset_icons_node_hold_png;
extern unsigned char asset_icons_node_delay_png[];
extern unsigned int size_asset_icons_node_delay_png;
extern unsigned char asset_icons_node_compare_png[];
extern unsigned int size_asset_icons_node_compare_png;
extern unsigned char asset_icons_node_select_png[];
extern unsigned int size_asset_icons_node_select_png;
extern unsigned char asset_icons_node_gate_png[];
extern unsigned int size_asset_icons_node_gate_png;
extern unsigned char asset_icons_node_split_png[];
extern unsigned int size_asset_icons_node_split_png;
extern unsigned char asset_icons_node_combine_png[];
extern unsigned int size_asset_icons_node_combine_png;
extern unsigned char asset_icons_node_colorize_png[];
extern unsigned int size_asset_icons_node_colorize_png;
extern unsigned char asset_icons_node_hsv_png[];
extern unsigned int size_asset_icons_node_hsv_png;
extern unsigned char asset_icons_node_gradient_png[];
extern unsigned int size_asset_icons_node_gradient_png;
extern unsigned char asset_icons_node_transform2d_png[];
extern unsigned int size_asset_icons_node_transform2d_png;
extern unsigned char asset_icons_node_render_png[];
extern unsigned int size_asset_icons_node_render_png;
extern unsigned char asset_icons_node_render_circle_png[];
extern unsigned int size_asset_icons_node_render_circle_png;
extern unsigned char asset_icons_node_render_line_png[];
extern unsigned int size_asset_icons_node_render_line_png;
extern unsigned char asset_icons_node_debug_png[];
extern unsigned int size_asset_icons_node_debug_png;
extern unsigned char asset_palettes_pal_256_rgb[];
extern unsigned int size_asset_palettes_pal_256_rgb;
extern unsigned char asset_graphs_default_gph[];
extern unsigned int size_asset_graphs_default_gph;

#endif /* ASSETS_EMBEDDED_DATA_H */
