/*
 * PS2 Live Graph Studio - Embedded Assets Header
 * assets_embedded.h - Declarations for embedded asset data
 *
 * Generated asset data is compiled directly into the ELF.
 * No host: filesystem access required at runtime.
 */

#ifndef ASSETS_EMBEDDED_H
#define ASSETS_EMBEDDED_H

#include <stddef.h>

/* ============================================================
 * Embedded Asset Entry
 * ============================================================ */
typedef struct {
    const char* name;       /* Asset path key (e.g., "ui/cursor.png") */
    const unsigned char* data;  /* Pointer to embedded data */
    size_t size;            /* Size in bytes */
} EmbeddedAsset;

/* ============================================================
 * Embedded Asset Table
 * ============================================================
 * Defined in assets_embedded_data.c (generated by build)
 * Terminated by entry with name == NULL
 */
extern const EmbeddedAsset g_embedded_assets[];
extern const int g_embedded_assets_count;

/* ============================================================
 * Lookup Function
 * ============================================================ */

/**
 * Find an embedded asset by name.
 * @param name  Asset path (e.g., "ui/cursor.png")
 * @return Pointer to EmbeddedAsset or NULL if not found
 */
const EmbeddedAsset* embedded_asset_find(const char* name);

#endif /* ASSETS_EMBEDDED_H */
